### ISSUE TITLE
epoch_20_000000文件需要怎么获取呢？

### ISSUE THREAD

**Issue by zhongshijun** [showlab/BYOC#2]
感谢作者开源代码。
请问，landmark2exp/checkpoints/facerecon/results/test_images/epoch_20_000000文件需要怎么获取呢？

**Comment by ChenVoid** [comment]
Thank you for your support! You can directly run the `image2bs/inference.py` or `image2bs/process_training_data.py` scripts. The `image2landmark()` and `landmark2exp()` functions within them will process the images to generate the `epoch_20_000000` folder you need.
