### ISSUE TITLE
blendshape version problem

### ISSUE THREAD

**Issue by P2Oileen** [showlab/BYOC#5]
Since there are many different versions of blendshapes, and ARKit is one of them, I would like to know if the 50-dimensional blendshape coefficients generated in your work can correspond to ARKit, similar to #3 
If so, the generated blendshape coefficients can be used on different 3D models. 
If not, I would also like to know which format your blendshape coefficients conform to, and how can I find any 3D models online that have the same blendshape keys as the male FBX file you provided?
Thank you very much.

**Comment by JosephPai** [comment]
Hi @P2Oileen , sorry for the late response. As the code is released under an organization account, I didn't receive email notification for the issue. Please feel free to email me if you have further questions.

Regarding the blendshape version, unfortunately, the current coefficients are not aligned with ARKit. That's also the reason we released the FBX file together. Our current coefficients are actually manually designed by ourselves in lab to facilitate facial expression animation. To transfer to ARKit, you may need to train the adapter model based on the ARKit blendshape following the method described in our paper.
